name : CICD

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nodejs-login-chat-app:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: docker version
        run: docker --version
      - name: pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-login-chat-app:latest
      - name: remove old container
        run: docker rm -f nodejs-login-chat-app
      - name: Run docker container
        run: docker run -d --name nodejs-login-chat-app -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/nodejs-login-chat-app:latest   